### ISSUE TITLE
Export Folder Structure

### ISSUE THREAD

**Issue by alexander-rebello** [glenn2223/vscode-live-sass-compiler#200]
I'm trying to do the following: I have this folder structure:

parent
|__ sass
|    |__ folder1
|    |    |__ file1.scss
|    |    |__ file2.scss
|    |__ folder2
|    |    |__ file1.scss
|    |    |__ file2.scss

And I want it to be exported to that folder structure:

parent
|__ sass
|    |__ folder1
|    |    |__ file1.scss
|    |    |__ file2.scss
|    |__ folder2
|    |    |__ file1.scss
|    |    |__ file2.scss
|__ css
|    |__ folder1
|    |    |__ file1.css
|    |    |__ file2.css
|    |__ folder2
|    |    |__ file1.css
|    |    |__ file2.css

Is that somehow possible? I read the settings documentation, but at least to me it wasn't very obviouse what I have to do.

**Comment by alexander-rebello** [comment]
Thanks for the quick response! No I get this error: "Live Sass Compiler: Unhandled error while compiling all files. Error message: EROFS: read-only file system, mkdir '/html'".

**Comment by glenn2223** [comment]
Hmm, that's not an error I've seen before. Seems like an issue with where it's trying to save to rather than an issue with the extension. However, just in case, can I see your `settings.json` file and your file structure? Also, do you have the project open anywhere different/special or just in one of your user folders?

**Comment by alexander-rebello** [comment]
```
{
	"workbench.startupEditor": "newUntitledFile",
	"workbench.colorCustomizations": {
		"[Material Theme Palenight High Contrast]": {}
	},
	"workbench.iconTheme": "material-icon-theme",
	"workbench.colorTheme": "Material Theme Palenight High Contrast",
	"workbench.editor.untitled.hint": "hidden",
	"editor.fontSize": 14,
	"editor.formatOnSave": true,
	"editor.largeFileOptimizations": false,
	"editor.defaultFormatter": "esbenp.prettier-vscode",
	"prettier.enableDebugLogs": true,
	"prettier.endOfLine": "auto",
	"prettier.useTabs": true,
	"files.autoSave": "onWindowChange",
	"explorer.confirmDragAndDrop": false,
	"explorer.confirmDelete": false,
	"discord.lowerDetailsEditing": "{workspace_and_folder}",
	"git.enableSmartCommit": true,
	"git.confirmSync": false,
	"liveServer.settings.CustomBrowser": "firefox",
	"liveServer.settings.useWebExt": true,
	"liveServer.settings.AdvanceCustomBrowserCmdLine": "",
	"liveServer.settings.donotShowInfoMsg": true,
	"liveServer.settings.donotVerifyTags": true,
	"tabnine.experimentalAutoImports": true,
	"html.format.indentInnerHtml": true,
	"liveSassCompile.settings.formats": [
		{
			"format": "compressed",
			"extensionName": ".min.css",
			"savePathReplacementPairs": {
				"/scss/compile/": "/css/"
			}
		}
	],
	"liveSassCompile.settings.autoprefix": true,
	"es6-css-minify.minifyOnSave": "yes",
	"prettier.printWidth": 500,
	"[sass]": {
		"editor.defaultFormatter": "syler.sass-indented"
	},
	"liveSassCompile.settings.showOutputWindowOn": "Trace",
	"python.defaultInterpreterPath": "python3"
}
```

All files are saved in my user folder (on mac).

**Comment by glenn2223** [comment]
Yeah, the setup looks okay and the folder location should be fine.

If you remove the `savePathReplacementPairs` setting I suggested, does it work?

What's in the output window when you save the file? _As you have `showOutputWindow` set to `trace`, there is detailed output when you save a file (you may need to clear the log before you save the file)_

**Comment by alexander-rebello** [comment]
I actually have 16 scss file and because of that the log is very long. I cut out everything from the first 15 Files (The log shows the same for all files, just different paths).

```
Command called: "liveSass.command.watchMySass"
--------------------
Starting to compile all files
--------------------
Changing status bar to: "Working on it..."
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: refugium
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 16 SASS files
--------------------
Compiling Sass/Scss Files: 
/Users/path/to/files/scss/compile/autumn/day.scss
/Users/path/to/files/scss/compile/autumn/night.scss
/Users/path/to/files/scss/compile/autumn/sunrise.scss
/Users/path/to/files/scss/compile/autumn/sunset.scss
/Users/path/to/files/scss/compile/spring/day.scss
/Users/path/to/files/scss/compile/spring/night.scss
/Users/path/to/files/scss/compile/spring/sunrise.scss
/Users/path/to/files/scss/compile/spring/sunset.scss
/Users/path/to/files/scss/compile/winter/day.scss
/Users/path/to/files/scss/compile/winter/night.scss
/Users/path/to/files/scss/compile/winter/sunrise.scss
/Users/path/to/files/scss/compile/winter/sunset.scss
/Users/path/to/files/scss/compile/summer/day.scss
/Users/path/to/files/scss/compile/summer/night.scss
/Users/path/to/files/scss/compile/summer/sunrise.scss
/Users/path/to/files/scss/compile/summer/sunset.scss
--------------------
Starting file 16 of 16
Path: /Users/path/to/files/scss/compile/summer/sunset.scss
--------------------
Found the workspace folder
Workspace Name: refugium
--------------------
Starting format 1 of 1
Settings: {"format":"compressed","extensionName":".min.css","savePathReplacementPairs":{"/scss/compile/":"/css/"}}
--------------------
Calculating file paths
Calculating the save paths for the css and map output files
Originating path: /Users/path/to/files/scss/compile/summer/sunset.scss
--------------------
No workspace provided
Using originating path: /Users/path/to/files/scss/compile/summer/sunset.scss
--------------------
Using segment replacement
Original path: /Users/path/to/files/scss/compile/summer/sunset.scss
Applying: /scss/compile/ => /css/
Checking directory exists
Directory: /css/summer/
NO PARENT DIRECTORY
Parent directory doesn't exist, we must create it
--------------------
Checking directory exists
Directory: /css
Directory doesn't exist, creating it
--------------------
Getting SASS files
Query pattern: undefined
Can be overwritten: true
--------------------
Checking folder 1 of 1
Folder: refugium
--------------------
No base folder override found. Keeping workspace folder
--------------------
Found 16 SASS files
--------------------
Converting error to a usable object
--------------------
Logging issue
Message: Unhandled error while compiling all files. Error message: EROFS: read-only file system, mkdir '/css'
--------------------
Saving logs to storage
--------------------
Switching UI state
--------------------
Changing status bar to: Watching
--------------------
Watching...
--------------------
```

Also without that setting everything works perfectly fine.

**Comment by alexander-rebello** [comment]
### UNEXPECTED ERROR

**Machine & Versions**
| Item | Value |
|----------------------:|:-----------------------|
| VS Code | v1.69.0 |
| Platform | darwin x64 |
| Node | 16.13.2 (103) |
| Live Sass | 5.5.0 |
<details><summary>Installed Extensions</summary><div>
- vscode.configuration-editing (1.0.0)<br/>- vscode.css-language-features (1.0.0)<br/>- vscode.debug-auto-launch (1.0.0)<br/>- vscode.emmet (1.0.0)<br/>- vscode.extension-editing (1.0.0)<br/>- vscode.git (1.0.0)<br/>- vscode.git-base (1.0.0)<br/>- vscode.github (0.0.1)<br/>- vscode.github-authentication (0.0.2)<br/>- vscode.ipynb (1.0.0)<br/>- vscode.json-language-features (1.0.0)<br/>- vscode.merge-conflict (1.0.0)<br/>- vscode.microsoft-authentication (0.0.1)<br/>- vscode.npm (1.0.1)<br/>- vscode.typescript-language-features (1.0.0)<br/>- Equinusocio.vsc-material-theme (33.5.0)<br/>- esbenp.prettier-vscode (9.5.0)<br/>- formulahendry.auto-rename-tag (0.1.10)<br/>- glenn2223.live-sass (5.5.0)<br/>- icrawl.discord-vscode (5.8.0)<br/>- olback.es6-css-minify (3.3.3)<br/>- PKief.material-icon-theme (4.19.0)<br/>- ritwickdey.LiveServer (5.7.5)<br/>- TabNine.tabnine-vscode (3.6.2)
</div></details>

**LOG**: 2022-07-11 15:29:20.857Z
```JSON
{
    "createdAt": "2022-07-11T15:29:20.857Z",
    "event": {
        "files": [
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/autumn/day.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/autumn/night.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/autumn/sunrise.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/autumn/sunset.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/spring/day.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/spring/night.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/spring/sunrise.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/spring/sunset.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/summer/day.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/summer/night.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/summer/sunrise.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/summer/sunset.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/winter/day.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/winter/night.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/winter/sunrise.scss",
            "/Users/rebelloa/Projects/VSCode/bs-themes/refugium/scss/compile/winter/sunset.scss"
        ],
        "error": {
            "stack": "Error: EROFS: read-only file system, mkdir '/scss'\n    at Object.mkdirSync (node:fs:1334:3)\n    at Function.MakeDirIfNotAvailable (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4247219)\n    at Function.MakeDirIfNotAvailable (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4247100)\n    at Function.MakeDirIfNotAvailable (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4247100)\n    at AppModel.<anonymous> (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4273260)\n    at Generator.next (<anonymous>)\n    at /Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4261311\n    at new Promise (<anonymous>)\n    at o (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4260997)\n    at AppModel.generateCssAndMapUri (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4270662)\n    at AppModel.<anonymous> (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4270400)\n    at Generator.next (<anonymous>)\n    at /Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4261311\n    at new Promise (<anonymous>)\n    at o (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4260997)\n    at /Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4270206\n    at Array.map (<anonymous>)\n    at AppModel.<anonymous> (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4270194)\n    at Generator.next (<anonymous>)\n    at /Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4261311\n    at new Promise (<anonymous>)\n    at o (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4260997)\n    at /Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4269963\n    at Array.map (<anonymous>)\n    at AppModel.<anonymous> (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4269951)\n    at Generator.next (<anonymous>)\n    at fulfilled (/Users/rebelloa/.vscode/extensions/glenn2223.live-sass-5.5.0/out/extension.js:2:4261065)",
            "message": "EROFS: read-only file system, mkdir '/scss'",
            "errno": -30,
            "syscall": "mkdir",
            "code": "EROFS",
            "path": "/scss"
        }
    }
}
```
=======================

**Comment by alexander-rebello** [comment]
Yes works prefectly fine! Thanks for your help. So it was just a bug?

**Comment by glenn2223** [comment]
Yes it was. I will push oficially tonight

**Comment by alexander-rebello** [comment]
Okay, perfect, thanks again.
